name: Main

on:
  push:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Pytorch
      run: pip install torch
      shell: bash

    - name: Install Poetry
      env:
        # renovate: datasource=pypi depName=poetry
        POETRY_VERSION: "1.4.2"
      run: curl -sSL https://install.python-poetry.org | python - -y
      shell: bash

    - name: Add Poetry to Path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Configure Poetry to not create a virtual environment
      run: poetry config virtualenvs.create false
      shell: bash

    - name: Install dependencies
      run: poetry install --no-interaction
      shell: bash

    - name: Check for dependency issues
      run: deptry .
      shell: bash
